writer:
  # type: file
  # filedir: concerts
  # type: api
  # uri: "http://localhost:5001/api/events"
  # uri_dryrun: "http://localhost:5001/api/events/validate"
  # uri_status: "http://localhost:5001/api/status"
  # write_status: true
  # batch_size: 50
  # user: croncert
  # password: croncert
  type: "api"
  uri: "https://api.concertcloud.live/api/events"
  uri_dryrun: "https://api.concertcloud.live/api/events/validate"
  uri_status: "https://api.concertcloud.live/api/status"
  write_status: true
  # The other parameters are defined as env variables.
