scrapers:
  - name: Schuur
    url: https://www.schuur.ch/programm/
    item: div.viz-event-list-container > div.viz-event-list > section.viz-event-list-box
    fields:
      - name: location
        value: Konzerthaus Schüür
      - name: city
        value: Lucerne
      - name: country
        value: Switzerland
      - name: type
        value: concert
      - name: sourceUrl
        value: https://www.schuur.ch/programm/
      - name: imageUrl
        type: url
        location:
          - selector: div.viz-event-box-image-container > a.viz-event-box-details-link > div.viz-event-box-image > img.lazyload
            attr: src
            # examples: ['https://www.schuur.ch/fileadmin/_processed_/f/5/csm_260203-Faber-16x9_947a41799f.jpg', 'https://www.schuur.ch/fileadmin/_processed_/9/6/csm_260204-KAA_0a20bccbd4.jpg', 'https://www.schuur.ch/fileadmin/_processed_/f/4/csm_260205-Bernhoft_393071a98b.jpg', 'https://www.schuur.ch/fileadmin/_processed_/a/b/csm_2026-NocheCubana-b3000_a1e5fa2131.jpg']
      - name: url
        type: url
        location:
          - selector: article > div.viz-event-box-title > div.viz-event-box-date > h3 > a.viz-event-box-details-link
            attr: href
            # examples: ['https://www.schuur.ch/programm/events/event-details/faber-03-02-2026-konzerthaus-schuur-luzern', 'https://www.schuur.ch/programm/events/event-details/kick-ass-award-04-02-2026-konzerthaus-schuur-luzern', 'https://www.schuur.ch/programm/events/event-details/bernhoft-05-02-2026-konzerthaus-schuur-luzern', 'https://www.schuur.ch/programm/events/event-details/noche-cubana-05-02-2026-konzerthaus-schuur-luzern']
      - name: title
        type: text
        location:
          - selector: article > div.viz-event-box-title > div.viz-event-box-date > h3 > a.viz-event-box-details-link > span.viz-event-name
            # examples: [Faber – Ausverkauft, Kick Ass Award, Bernhoft, Noche Cubana]
      - name: comment
        type: text
        location:
          - selector: article > div.viz-event-box-title > div.viz-event-box-date > span.viz-event-headline
            # examples: [«Addio Addio»-Tour, 'Verjüngungsinitiative: z''alt für Politik – das crazy', '«The Cause I Wanna»-Tour 2026 / Support: Ay Wing', Salsa con el DJ Ivan]
        can_be_empty: true
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
              time: true
            location:
              selector: article > div.viz-event-box-title > div.viz-event-box-date > div.viz-event-date-and-sub-container > div.viz-event-date
              # examples: ['Di. 03. Feb. 2026 – 19:00', 'Mi. 04. Feb. 2026 – 19:00', 'Do. 05. Feb. 2026 – 19:00', 'Do. 05. Feb. 2026 – 21:00']
            layout:
              - Mon. 2. Jan. 2006 – 15:04
              - Mon. 2. January 2006 – 15:04
        date_location: CET
        date_language: de_DE
    fetcher:
      type: static

  - name: Bar59
    url: https://www.bar59.ch/
    item: body > div.container > div > div.contentBlock.events > div.day
    fields:
      - name: "location"
        value: "Bar 59"
      - name: "city"
        value: "Lucerne"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.bar59.ch/
      - name: "url"
        value: https://www.bar59.ch/
      - name: title
        type: text
        location:
          - selector: div.event:nth-child(2) > h3.collapsed > span
      - name: imageUrl
        type: url
        location:
          - selector: div.col-xs-12.col-md-9.col-md-pull-3.left > img
            attr: src
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.event:nth-child(2) > h3.collapsed > small
            layout:
              - "15:04"
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.daylabel > span.big
            layout:
              - Monday 2.1.2006
        date_location: CET
        date_language: de_DE
    fetcher:
      type: dynamic
      page_load_wait_ms: 5000
    paginator:
      location:
        selector: div.paginatorContainer > div > button:nth-child(3)
      max_pages: 4

  - name: Neubad
    url: https://neubad.org/veranstaltungen?f%5B0%5D=kategorie_der_veranstaltung_%3AKonzert
    item: div.view-content > div.w3-section > div.cal.item-list
    fields:
      - name: "location"
        value: Neubad
      - name: "city"
        value: "Lucerne"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://neubad.org/veranstaltungen?f%5B0%5D=kategorie_der_veranstaltung_%3AKonzert
      - name: title
        type: text
        location:
          - selector: div.vorschau > a > span.title
      - name: url
        type: url
        location:
          selector: span.field-content > div.vorschau > a
          attr: href
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.views-field.views-field-field-datum-event-3 > span.field-content
            layout:
              - "15:04"
          - covers:
              day: true
              month: true
            location:
              selector: h3
            layout:
              - Mon. 2. January
        date_location: CET
        date_language: de_DE
        guess_year: true

  - name: Jazzkantine
    url: https://www.jazzkantine.com/veranstaltungen
    item: div.eventlist.eventlist--upcoming > article.eventlist-event.eventlist-event--hasimg.eventlist-hasimg.is-loaded
    fields:
      - name: "location"
        value: Jazzkantine
      - name: "city"
        value: "Lucerne"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.jazzkantine.com/veranstaltungen
      - name: comment
        type: text
        can_be_empty: true
        location:
          - selector: div.eventlist-column-info > div.eventlist-description > div.columns-12.sqs-grid-12.sqs-layout > div.row.sqs-row > div.col.span-12.sqs-col-12 > div.html-block.sqs-block.sqs-block-html > div.sqs-block-content > div.sqs-html-content > p
            entire_subtree: true
      - name: title
        type: text
        location:
          - selector: div.eventlist-column-info > h1.eventlist-title > a.eventlist-title-link
      - name: url
        type: url
        location:
          - selector: div.eventlist-column-info > h1.eventlist-title > a.eventlist-title-link
            attr: href
      - name: imageUrl
        type: url
        location:
          - selector: a.content-fill.eventlist-column-thumbnail > img
            attr: src
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.eventlist-column-info > ul.event-meta.eventlist-meta > li.event-meta-item.eventlist-meta-item.eventlist-meta-time > span.event-time-localized > time.event-time-localized-start
            layout:
              - "15:04"
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.eventlist-column-info > ul.event-meta.eventlist-meta > li.event-meta-item.eventlist-meta-date.eventlist-meta-item > time.event-date
            layout:
              - Monday, 2. January 2006
        date_location: CET
        date_language: de_DE
    fetcher:
      type: dynamic
      page_load_wait_ms: 2000
